### ISSUE TITLE
After running some notebooks cells gives an error "TypeError: Cannot read properties of undefined (reading 'status')"

### ISSUE THREAD

**Issue by ktakanopy** [paiqo/Databricks-VSCode#196]
**Describe the bug**
After running some notebooks cells gives an error "TypeError: Cannot read properties of undefined (reading 'status')"

**To Reproduce**
1. Download Databricks extension and databricks power tools
2. Connect to a cluster
3. Create a notebook.ipynb 
4. Run some cells in the notebook connected to a cluster.
5. You will receive an error "TypeError: Cannot read properties of undefined (reading 'status')"

**Screenshots**
![Screenshot 2024-07-05 at 10 48 41](https://github.com/databricks/databricks-vscode/assets/10998362/086cb32a-5e91-40ac-8ac6-18e89b488e63)

**System information:**

1. MacOs Sonoma 14.5
2. Databricks Extension Version: 1.3.1

**Databricks Extension Logs**
- Which log file do I need to send? 

**Additional context**

**Comment by kupalinka-lis** [comment]
I have the same issue with the same system info

**Comment by gbrueckl** [comment]
Please check the logs under Outputs -> databricks.vscode and post the here (remove sensitive information if necessary)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ktakanopy** [comment]
Hi @gbrueckl here the logs (I think it's the correct, please tell me if not)

```2024-07-19 09:50:12.124 [error] Error: Source IP address: ***.***.**.*** is blocked by Databricks IP ACL for workspace: ***************
	at parseErrorFromResponse (/path/to/.vscode/extensions/databricks.databricks-1.3.1-darwin-x64/out/extension.js:1855:14)
	at fn (/path/to/.vscode/extensions/databricks.databricks-1.3.1-darwin-x64/out/extension.js:2386:63)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async retry3 (/path/to/.vscode/extensions/databricks.databricks-1.3.1-darwin-x64/out/extension.js:1735:20)
	at async ApiClient8.request (/path/to/.vscode/extensions/databricks.databricks-1.3.1-darwin-x64/out/extension.js:2362:26)
	at async ClustersService._get (/path/to/.vscode/extensions/databricks.databricks-1.3.1-darwin-x64/out/extension.js:27967:16)
	at async ClustersService.get (/path/to/.vscode/extensions/databricks.databricks-1.3.1-darwin-x64/out/extension.js:27978:32)
	at async _Cluster.refresh (/path/to/.vscode/extensions/databricks.databricks-1.3.1-darwin-x64/out/extension.js:116965:20)
	at async Timeout._onTimeout (/path/to/.vscode/extensions/databricks.databricks-1.3.1-darwin-x64/out/extension.js:119248:7)
	```

**Comment by gbrueckl** [comment]
so the error message you posted comes from the original Databricks extension `[databricks.databricks](https://marketplace.visualstudio.com/items?itemName=databricks.databricks)` and is not related to this extension.
Can you check which Kernel you are using for your Notebook?

the logs related to this extension can be found here:
![image](https://github.com/user-attachments/assets/25cfe43c-3360-406f-b494-e91d53fdf46e)

**Comment by rgalljamov** [comment]
I have the same issue on Windows and get the following logs (@gbrueckl, thank you for explaining where to find the right logs):
```
POST 1.2/commands/execute --> {"clusterId":"0326-150543-8brhnzrc","language":"python","contextId":"2674181048795868090","command":"import numpy as np\n\nimport matplotlib.pyplot as plt\n\n# %matplotlib inline\n\n# Generate random values\nx = np.random.rand(1000)\ny = np.random.rand(1000)\n\n# Create scatter plot\nplt.scatter(x, y, alpha=0.0125)\n\n# Add labels and title\nplt.xlabel('X')\nplt.ylabel('Y')\nplt.title('Random Scatter Plot')\n\n# Display the plot\nplt.show()"}
Response: {"error_code":403,"message":"JWT has expired"} ...
GET 1.2/commands/status --> {"clusterId":"0326-150543-8brhnzrc","contextId":"2674181048795868090"}
GET 1.2/commands/status failed! ERROR: " (403) Forbidden
ERROR: Error - Forbidden
```
It always happens when you pause programming for some time and come back later. Restarting VS Code solves the issue, but it would be great if the restart wouldn't be required.

Thank you for the great extension and in advance for the support.

**Comment by gbrueckl** [comment]
@rgalljamov  so this error is related to this extension and i can have a look.
its basically complaining about an expired JWT token which I guess comes from the OAuth that used behind the scenes. You are using the Azure Connection Manager, right?

the token probably expires after 1 hour and we dont have any refresh in place yet as this only happens for the Azure Connection Manager 
but we should be able to fix this :)

**Comment by rgalljamov** [comment]
Thank you very much for the swift reply and support @gbrueckl! 

I'm using the official Databricks Extension in the newest version and OAuth U2M authentification. Therefore, your extension worked right away after installation, which was a great positive surprise. The expiration duration might be below an hour but I have not tested it yet.

**Comment by kupalinka-lis** [comment]
Just checked the error logs - I have the same JWT issue
```
Response: {"error_code":403,"message":"JWT has expired"} ...
GET 1.2/commands/status --> {"clusterId":"...","contextId":"..."}
GET 1.2/commands/status failed! ERROR: " (403) Forbidden
ERROR: Error - Forbidden

```
Thanks for looking on it!

**Comment by sreekanth9999** [comment]
were anyone able to fix this issue?

**Comment by gbrueckl** [comment]
I just published v2.3.5 to the marketplace which should hopefully fix this issue
we are now updating the JWT token every 30 minutes

**Comment by jaakko-paavola** [comment]
I get a slightly different error from trying to execute cells every 20 mins or so:
"TypeError: Cannot read properties of undefined (reading '**error**')"
and the output log for paiqo.databricks-vscode has:
"""
OST 1.2/commands/execute --> {"clusterId":"1111-222222-3333333","language":"python","contextId":"4444444444444444444","command":"print(df)"}
ERROR: p - Invalid response body while trying to fetch https://xxxxxxxx.cloud.databricks.com/api/1.2/commands/execute: 
"""

It may be giving me this error for several minutes for any cell, but eventually it will recover, maybe following the appearance of this in the output log:
"""
Refreshing Databricks API Headers ...
"""

I remember seeing a text entry somewhere in the output log saying the headers are refreshed every 1800 seconds. Is there some way to make this more frequent?

**Comment by gbrueckl** [comment]
may I ask if other features of the original Databricks extension still work at the time when you face those issues?
e.g. choosing a different cluster, starting/stopping a cluster, etc.

just want to make sure its not related to the token that we get from the original Databricks extension

**Comment by gbrueckl** [comment]
ok, did some more investigation:
the token we get from the original Databricks extension is valid for 1h and is refreshed automatically before it expires
as of now, I simply get the current token every 30 minutes
now it can happen that I get the token right before it times out - meaning for the next 30 minutes I will use an invalid token and all API calls fail
I think this is what happens in your case 

I will see what I can do

**Comment by gbrueckl** [comment]
is there actually a specific reason why you cannot/do not want to use notebooks?

**Comment by jaakko-paavola** [comment]
> ok, did some more investigation: the token we get from the original Databricks extension is valid for 1h and is refreshed automatically before it expires as of now, I simply get the current token every 30 minutes now it can happen that I get the token right before it times out - meaning for the next 30 minutes I will use an invalid token and all API calls fail I think this is what happens in your case
> 
> I will see what I can do

After a couple more days of experience with this problem, I can say this:
- The error happens in an instant; I may have just executed a cell successfully a second ago but then the next one throws the error.
- The error persists for what I would estimate is 3-5 mins. I can try to time the exact duration next time I encounter this, if that would be useful information. Perhaps it's the same duration every time, but not sure.
- So most likely the cause is not the 30-minute token then.

**Comment by gbrueckl** [comment]
in the new solution I would decode the token to see when it expires
then wait until it expiry time and request a new token from the original extension which seems to update the token a couple of seconds before it expires 
this should hopefully solve the problem but I still need some more testing

**Comment by jaakko-paavola** [comment]
> is there actually a specific reason why you cannot/do not want to use notebooks?

I think you meant to post this here #202. I have at least three reasons to prefer the interactive window over notebook:
1) VsCode is much snappier/more responsive to use when dealing with a .py file instead of a .ipynb.
2) Debugging interactively is more convenient when you can send the current line or anything you paint with the cursor to be executed. Much faster than adding a cell above or below and then copying those things there and then executing the cell, and then removing the redundant cell.
3) I started coding data stuff with RStudio, so I got used to the interactive window.

**Comment by gbrueckl** [comment]
can you try this build: https://gbpublic001.blob.core.windows.net/files/databricks-vscode-2.3.6.vsix 
it should fix the expiring token issue

**Comment by jaakko-paavola** [comment]
I can report that I no longer get this error. But the fix to the issue was not the build you made available above, because I still got the error after installing it. Instead, I think I managed to fix the error with proxy configurations in VsCode settings that made things work with my company's proxy server. Anyway, thanks for the help for troubleshooting and making the Databricks kernel available in the interactive window, which has a huge benefit for me!

**Comment by gbrueckl** [comment]
closing as it seems to work now
